### ISSUE TITLE
Return object from a Fold()

### ISSUE THREAD

**Issue by Burf2k** [Liftric/cognito-idp#64]
Really sorry to ask, but I haven't done Kotlin for a few years so .fold is puzzling me.  How do I return something out of a fold, from your samples, getUser gets the user, brilliant but how do I return it (User is my own class which takes UserAtributes)

```
    suspend fun getUser(accessToken: String) : User  {

        provider.getUser(accessToken ).fold(
            onSuccess = {
                print("login")
                currentUser = User.populateUserDetails(it)
                
                // does not compile as expects Unit, not User object
                return@fold currentUser
            },
            onFailure = {
                // Handle exceptions
                print(it.message)
            }
        )
    }
```

**Comment by Burf2k** [comment]
I asked StackoverFlow and that answer doesn't work, there must be a way to return something useful
https://stackoverflow.com/questions/76101500/kotlin-returning-an-object-from-a-fold-closure/76103361#76103361

**Comment by benjohnde** [comment]
This is more a question on Kotlin and how to work with suspend / Coroutines. But seeing the latest answer in this SO post I would infer that your problem is solved.

**Comment by Burf2k** [comment]
Thank you Ben, I just assumed there was a way we could use onSuccess and onFailure

**Comment by gaebel** [comment]
Hi @Burf2k, there's indeed an issue with the fold extension. Since kotlin.Result couldn't get returned in the past and type information still gets lost when exported, we implemented our own Result type. The fold extension doesn't return anything from onSuccess and onFailure.

**Comment by Burf2k** [comment]
So do I need to use your library or wait for a fix?

**Comment by gaebel** [comment]
You could use getOrThrow to get the user, and wrap the call in a try/catch block to handle exceptions.

**Comment by Burf2k** [comment]
Thanks, glad I was not using Fold wrong

**Comment by Ingwersaft** [comment]
Fold is just like a promise in the JS world, you could wrap the "callbacks" with [suspendCancellableCoroutine](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/suspend-cancellable-coroutine.html)
